#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.3 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue May 25 16:34:59 SAST 2021
# SW Build 3173277 on Wed Apr  7 05:07:21 MDT 2021
#
# IP Build 3174024 on Wed Apr  7 23:42:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 22d382e39e0e43d3af3d346c2598215c --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L unisims_ver -L secureip --snapshot testBench_behav xil_defaultlib.testBench xil_defaultlib.glbl -log elaborate.log"
xelab -wto 22d382e39e0e43d3af3d346c2598215c --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L unisims_ver -L secureip --snapshot testBench_behav xil_defaultlib.testBench xil_defaultlib.glbl -log elaborate.log

